name: Linuxtips challenge 1

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image'
        type: 'string'
        required: true

jobs:
  earth:
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker image pull "${{ inputs.image }}"
      - name: List all images 
        run: docker images 