name: Linuxtips workflow

on: 
  push:
      branches:
          - main
jobs:
  mars:
    runs-on: ubuntu-latest
    steps:
      - name: Check ubuntu version
        run: cat /etc/os-release
      
      - name: Who're u ?
        run: echo "Who are you ?" | uname -r
      
      - name: I'am 
        run: uname 
